In [15]:
# importing the dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [16]:
class Logistic_Regression():
    def __init__(self,learning_rate,iteration):
        self.learning_rate=learning_rate
        self.iteration=iteration
    def fit(self,X,Y):
        self.m,self.n=X.shape
        self.w=np.zeros(self.n)
        self.b=0
        self.x=X
        self.y=Y
        for i in range(self.iteration):
            self.update_weights()

    def update_weights(self,):
        z=self.x.dot(self.w)+self.b
        Y=1/(1+np.exp(-z))
        dw=(1/self.m)*np.dot(self.x.T,Y-self.y)
        db=(1/self.m)*np.sum(Y-self.y)
        self.w=self.w-self.learning_rate*dw
        self.b=self.b-self.learning_rate*db
    def predict(self,x):
        z=x.dot(self.w)+self.b
        Y_pred=1/(1+np.exp(-z))
        Y_pred=np.where(Y_pred>=0.5,1,0)
        return Y_pred

In [17]:
user=pd.read_csv(r"users.csv")
fuser=pd.read_csv(r"fusers.csv")
print(user.shape)
print(fuser.shape)

(1481, 34)
(1337, 34)

In [18]:
user["outcome"]=pd.DataFrame(data=np.ones((1481,1),dtype=int))
user.head()

,id,name,screen_name,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,url,...,profile_background_image_url,profile_background_color,profile_link_color,utc_offset,protected,verified,description,updated,dataset,outcome
0,3610511,Davide Dellacasa,braddd,20370,5470,2385,145,52,Fri Apr 06 10:58:22 +0000 2007,http://braddd.tumblr.com,...,http://a0.twimg.com/profile_background_images/...,BADFCD,FF0000,3600.0,NaN,NaN,Founder of http://www.screenweek.it & http://w...,2015-02-14 10:54:49,E13,1
1,5656162,Simone Economo,eKoeS,3131,506,381,9,40,Mon Apr 30 15:08:42 +0000 2007,http://www.lineheight.net/,...,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,3600.0,NaN,NaN,BSc degree (cum laude) in Computer Engineering...,2015-02-14 10:54:49,E13,1
2,5682702,tacone,tacone_,4024,264,87,323,16,Tue May 01 11:53:40 +0000 2007,http://t.co/LKrl1dZE,...,http://a0.twimg.com/profile_background_images/...,1A1B1F,2FC2EF,3600.0,NaN,NaN,Cogito ergo bestemmio.,2015-02-14 10:54:49,E13,1
3,6067292,alesaura,alesstar,40586,640,622,1118,32,Tue May 15 16:55:16 +0000 2007,http://alesstar.wordpress.com/,...,http://a0.twimg.com/images/themes/theme4/bg.gif,0099B9,0099B9,3600.0,NaN,NaN,"Se la vita ti dà sarde, scapocciale!",2015-02-14 10:54:49,E13,1
4,6015122,Angelo,PerDiletto,2016,62,64,13,0,Sun May 13 19:52:00 +0000 2007,http://www.flickr.com/per_diletto,...,http://a0.twimg.com/images/themes/theme18/bg.gif,ACDED6,038543,3600.0,NaN,NaN,Je me souviens,2015-02-14 10:54:49,E13,1

In [19]:
fuser["outcome"]=pd.DataFrame(data=np.zeros((1337,1),dtype=int))
fuser.head()

,id,name,screen_name,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,url,...,profile_background_image_url,profile_background_color,profile_link_color,utc_offset,protected,verified,description,updated,dataset,outcome
0,370098498,pirfectmoses,pirfectmoses,24,4,588,16,0,Thu Sep 08 13:20:35 +0000 2011,NaN,...,http://a0.twimg.com/profile_background_images/...,C6E2EE,1F98C7,NaN,NaN,NaN,NaN,2015-02-14 10:40:01,INT,0
1,37384589,SAK Nair,bsknair1967,656,57,693,597,0,Sun May 03 07:35:13 +0000 2009,NaN,...,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,NaN,NaN,NaN,in Kuwait with my buetiful family.,2015-02-14 10:40:01,INT,0
2,72110028,Deepak,dedjven,1234,15,104,1150,0,Sun Sep 06 19:50:08 +0000 2009,NaN,...,http://a0.twimg.com/images/themes/theme14/bg.gif,131516,009999,-39600.0,NaN,NaN,NaN,2015-02-14 10:40:01,INT,0
3,82885728,Marcos Vinicius,BrowAlves,573,14,227,530,0,Fri Oct 16 14:02:48 +0000 2009,NaN,...,http://a0.twimg.com/profile_background_images/...,C0DEED,0084B4,NaN,NaN,NaN,NaN,2015-02-14 10:40:01,INT,0
4,110120789,Shri Kant Kanaujia,kanaujiask,675,18,519,653,0,Sun Jan 31 12:08:41 +0000 2010,NaN,...,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,19800.0,NaN,NaN,NaN,2015-02-14 10:40:01,INT,0

In [20]:
total_user=pd.concat([user,fuser],ignore_index=True)
total_user.shape

(2818, 35)

In [21]:
user.head()

,id,name,screen_name,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,url,...,profile_background_image_url,profile_background_color,profile_link_color,utc_offset,protected,verified,description,updated,dataset,outcome
0,3610511,Davide Dellacasa,braddd,20370,5470,2385,145,52,Fri Apr 06 10:58:22 +0000 2007,http://braddd.tumblr.com,...,http://a0.twimg.com/profile_background_images/...,BADFCD,FF0000,3600.0,NaN,NaN,Founder of http://www.screenweek.it & http://w...,2015-02-14 10:54:49,E13,1
1,5656162,Simone Economo,eKoeS,3131,506,381,9,40,Mon Apr 30 15:08:42 +0000 2007,http://www.lineheight.net/,...,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,3600.0,NaN,NaN,BSc degree (cum laude) in Computer Engineering...,2015-02-14 10:54:49,E13,1
2,5682702,tacone,tacone_,4024,264,87,323,16,Tue May 01 11:53:40 +0000 2007,http://t.co/LKrl1dZE,...,http://a0.twimg.com/profile_background_images/...,1A1B1F,2FC2EF,3600.0,NaN,NaN,Cogito ergo bestemmio.,2015-02-14 10:54:49,E13,1
3,6067292,alesaura,alesstar,40586,640,622,1118,32,Tue May 15 16:55:16 +0000 2007,http://alesstar.wordpress.com/,...,http://a0.twimg.com/images/themes/theme4/bg.gif,0099B9,0099B9,3600.0,NaN,NaN,"Se la vita ti dà sarde, scapocciale!",2015-02-14 10:54:49,E13,1
4,6015122,Angelo,PerDiletto,2016,62,64,13,0,Sun May 13 19:52:00 +0000 2007,http://www.flickr.com/per_diletto,...,http://a0.twimg.com/images/themes/theme18/bg.gif,ACDED6,038543,3600.0,NaN,NaN,Je me souviens,2015-02-14 10:54:49,E13,1

In [22]:
user.tail()

,id,name,screen_name,statuses_count,followers_count,friends_count,favourites_count,listed_count,created_at,url,...,profile_background_image_url,profile_background_color,profile_link_color,utc_offset,protected,verified,description,updated,dataset,outcome
1476,1127280169,Frilaif Official,frilaif,49,208,124,14,2,Mon Jan 28 07:13:47 +0000 2013,http://t.co/IkqfPF32pr,...,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,NaN,NaN,NaN,Sex and Erotic Advisor. Sexual health is a sta...,2015-02-14 10:54:49,E13,1
1477,1156344000,♔♥HeartsQueen♥♔,Stronzetta__,66,22,55,0,0,Thu Feb 07 07:27:08 +0000 2013,NaN,...,http://a0.twimg.com/images/themes/theme10/bg.gif,642D8B,740CC4,NaN,NaN,NaN,Se avessi seguito tutte le regole non sarei ma...,2015-02-14 10:54:49,E13,1
1478,1169114810,angelagervasi,angelagervasi2,4,0,4,3,0,Mon Feb 11 14:50:19 +0000 2013,NaN,...,http://a0.twimg.com/images/themes/theme1/bg.png,C0DEED,0084B4,NaN,NaN,NaN,"mamma e giovane nonna,laureata,amante del teat...",2015-02-14 10:54:49,E13,1
1479,1212975186,Midnight,Movie1O,3,2,4,0,0,Sat Feb 23 17:46:55 +0000 2013,NaN,...,http://a0.twimg.com/profile_background_images/...,FFFFFF,000000,NaN,NaN,NaN,"If you don't shut your fucking mouth, I will k...",2015-02-14 10:54:49,E13,1
1480,1213937306,ʸᵒᵘ,xjawaadscookie,2568,351,341,318,2,Sat Feb 23 23:17:08 +0000 2013,NaN,...,http://a0.twimg.com/profile_background_images/...,FFFFFF,2BF00C,3600.0,NaN,NaN,@onedirection I JUST WANNA SAY A MASSIVE THANK...,2015-02-14 10:54:49,E13,1

In [23]:
print(total_user.isnull().sum())

id                                       0
name                                     0
screen_name                              0
statuses_count                           0
followers_count                          0
friends_count                            0
favourites_count                         0
listed_count                             0
created_at                               0
url                                   2355
lang                                     0
time_zone                             1749
location                               547
default_profile                       1090
default_profile_image                 2810
geo_enabled                           2097
profile_image_url                        0
profile_banner_url                    1831
profile_use_background_image            58
profile_background_image_url_https       0
profile_text_color                       0
profile_image_url_https                  0
profile_sidebar_border_color             0
profile_background_tile               2329
profile_sidebar_fill_color               0
profile_background_image_url             0
profile_background_color                 0
profile_link_color                       0
utc_offset                            1749
protected                             2818
verified                              2818
description                            271
updated                                  0
dataset                                  0
outcome                                  0
dtype: int64

In [24]:
x=total_user.drop(columns='outcome',axis=1)
y=total_user['outcome']

In [25]:
# spliting training data and testing data
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=3)
model=Logistic_Regression(learning_rate=0.02,iteration=1000)
modlel1= LogisticRegression()

In [28]:
#model.fit(xtrain,ytrain)
model1=LogisticRegression()

In [29]:
modlel1.fit(xtrain,ytrain)

ValueError: could not convert string to float: 'Kelley Holt'